import { STATE_VERSION, type AppState, type Node } from "./types";

function node(
  ticker: string,
  name: string,
  assetClass: Node["class"],
  status: Node["status"],
  thesis: string,
  failureCondition: string,
  links: Node["links"] = [],
): Node {
  return {
    id: `node-${ticker.toLowerCase()}`,
    ticker,
    name,
    class: assetClass,
    thesis,
    failureCondition,
    status,
    manualPriceUsd: null,
    manualPriceUpdatedAt: null,
    links,
  };
}

export function createSeedState(now = "2026-09-11T12:00:00.000Z"): AppState {
  return {
    version: STATE_VERSION,
    treasury: {
      units: 26000,
      asset: "XRP",
      venue: "Xaman",
      locationNote: "Currently in a Flare vault",
      estimatedDailyReward: 1,
      manualUsdPerXrp: null,
      provenance: "founder-reported",
      updatedAt: now,
    },
    venues: [
      {
        id: "venue-coinbase",
        name: "Coinbase",
        role: "General",
        notes: "General exchange venue. Import of statements is a later phase.",
      },
      {
        id: "venue-xaman",
        name: "Xaman",
        role: "Treasury",
        notes: "Treasury wallet of record for XRP. Public address watch is future work.",
      },
      {
        id: "venue-metamask",
        name: "MetaMask",
        role: "Secondary — Flare DeFi play",
        notes: "Secondary surface for Flare DeFi. Not the vault of record.",
      },
    ],
    nodes: [
      node(
        "BTC",
        "Bitcoin",
        "digital",
        "watch",
        "Long-duration monetary reserve. Fund only from realized rewards after treasury principal is stable.",
        "Thesis fails if a funded position would require spending XRP principal, or if custody cannot be described in one sentence.",
      ),
      node(
        "ETH",
        "Ethereum",
        "digital",
        "watch",
        "Settlement and DeFi optionality. Watch until rewards can size a position without touching XRP principal.",
        "Abandon if gas, custody, or protocol risk cannot be named before funding.",
      ),
      node(
        "SOL",
        "Solana",
        "digital",
        "watch",
        "High-throughput L1. Unfunded watch until size, venue, and failure condition are written down.",
        "Do not fund while the written size is blank or while treasury rewards are still needed to rebuild principal.",
      ),
      node(
        "XRP",
        "XRP",
        "digital",
        "funded",
        "Operating treasury rail. Keep principal intact. Realized Flare-vault rewards may later fund other nodes.",
        "Reduce or exit the yield overlay if principal is at risk, rewards cannot be reconciled, or custody leaves Xaman/Flare undocumented.",
        [
          {
            targetTicker: "FLR",
            kind: "depends-on",
            note: "Flare vault overlay for yield — secondary to XRP principal.",
          },
        ],
      ),
      node(
        "SUI",
        "Sui",
        "digital",
        "watch",
        "Move-based L1 option. Thesis is incomplete — tracking only.",
        "Remain unfunded until a specific use and a maximum loss are written.",
      ),
      node(
        "FLR",
        "Flare",
        "digital",
        "watch",
        "Venue layer for XRP vault / DeFi yield. Secondary to treasury preservation. MetaMask is a play surface, not the books.",
        "Stop the overlay if yield requires locking principal on terms you cannot explain, or if FLR exposure becomes the position instead of XRP.",
        [
          {
            targetTicker: "XRP",
            kind: "related",
            note: "Yield venue for the XRP treasury, not the books of record.",
          },
        ],
      ),
      node(
        "PWR",
        "Quanta Services",
        "physical",
        "watch",
        "US equity. Electrical infrastructure exposed to grid and compute-load buildout (Quanta).",
        "Drop to none if the thesis becomes a trade without a holding period and a max loss, or if funding would tap XRP principal.",
      ),
      node(
        "ETN",
        "Eaton",
        "physical",
        "watch",
        "US equity. Power management and electrical equipment (Eaton).",
        "Invalid if position sizing is not funded from realized rewards or if the company-level thesis cannot be restated in two lines.",
      ),
      node(
        "VRT",
        "Vertiv",
        "physical",
        "watch",
        "US equity. Data-center thermal and power infrastructure (Vertiv).",
        "Watch only until a written entry price band and a reason to sell exist.",
      ),
      node(
        "GEV",
        "GE Vernova",
        "physical",
        "watch",
        "US equity. Grid and generation transition (GE Vernova).",
        "Do not fund as a momentum ticker. Require a cycle-length holding thesis first.",
      ),
      node(
        "CEG",
        "Constellation Energy",
        "physical",
        "watch",
        "US equity. Contracted power and nuclear generation (Constellation).",
        "Failure if the thesis depends on a single headline rather than contracted cash flows you can point to.",
      ),
      node(
        "HUBB",
        "Hubbell",
        "physical",
        "watch",
        "US equity. Electrical products into construction and utility channels (Hubbell).",
        "Remain unfunded until rewards coverage and a boring holding period are specified.",
      ),
    ],
    ledger: [
      {
        id: "led-open",
        date: "2026-08-15",
        amount: 26000,
        fee: 0,
        note: "Opening treasury balance on Xaman / Flare vault. Founder-reported; not chain-verified.",
        classification: "principal",
        applyToBalance: false,
        createdAt: "2026-08-15T15:00:00.000Z",
      },
      {
        id: "led-d1",
        date: "2026-09-01",
        amount: 1.0,
        fee: 0,
        note: "Approx daily Flare-vault reward (founder-reported, ~1 XRP/day).",
        classification: "reward",
        applyToBalance: false,
        createdAt: "2026-09-01T18:00:00.000Z",
      },
      {
        id: "led-w1",
        date: "2026-09-08",
        amount: 7.14,
        fee: 0.02,
        note: "Weekly reward sweep (founder-reported). Fee is a placeholder for network/venue cost.",
        classification: "reward",
        applyToBalance: false,
        createdAt: "2026-09-08T18:30:00.000Z",
      },
    ],
    decisions: [
      {
        id: "dec-vault",
        question: "Keep XRP principal in the Flare vault, or hold liquid on Xaman?",
        options: "Keep in vault and harvest rewards · Hold liquid on Xaman · Split",
        status: "decided",
        decision:
          "Keep principal in the Flare vault. Do not spend principal. Use realized rewards later to fund other nodes.",
        date: "2026-08-20",
        createdAt: "2026-08-20T16:00:00.000Z",
      },
      {
        id: "dec-next-node",
        question: "Which node should be the first funded position after XRP?",
        options: "BTC · ETH · FLR overlay only · A physical ticker · None yet",
        status: "pending",
        decision: "",
        date: "2026-09-11",
        createdAt: now,
      },
      {
        id: "dec-youtube",
        question: "Stand up YouTube as an earning machine this quarter?",
        options: "Not now · Stub only · Commit to a publishing cadence",
        status: "pending",
        decision: "",
        date: "2026-09-11",
        createdAt: now,
      },
    ],
    settings: {
      operatorName: "Andres López",
      operatingPriority:
        "Build and add to treasury. Keep principal. Use realized rewards later to fund other nodes.",
      xrplWatchAddress: "",
      showYoutubeStub: true,
    },
  };
}
