-- Domain tables for Resonance stores.
-- Idempotent: safe to re-run. New domains (money, fitness, fight results)
-- land as later files in this folder. See db/README.md.

CREATE TABLE IF NOT EXISTS schema_migrations (
  id text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS store_meta (
  domain text PRIMARY KEY,
  version integer NOT NULL,
  updated_at timestamptz NOT NULL,
  seeded_at timestamptz
);

-- Operator log rows. One row per fill. /log reads this table
-- (and the operator_log view). Idempotent ingest key is (source, external_id).
CREATE TABLE IF NOT EXISTS fills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  external_id text NOT NULL,
  filled_at timestamptz NOT NULL,
  symbol text NOT NULL,
  side text,
  quantity numeric,
  price numeric,
  venue text,
  sleeve text,
  result text NOT NULL,
  log_only boolean NOT NULL DEFAULT false,
  note text,
  payload jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source, external_id)
);

CREATE TABLE IF NOT EXISTS sleeve_prints (
  ticker text NOT NULL,
  sleeve_id text NOT NULL,
  quantity text NOT NULL,
  PRIMARY KEY (ticker, sleeve_id)
);

-- id stays the primary key. order_id is the idempotency key (falls back to id).
CREATE TABLE IF NOT EXISTS bets (
  id text PRIMARY KEY,
  order_id text NOT NULL,
  event text NOT NULL,
  fight text NOT NULL,
  fight_slug text NOT NULL,
  pick text NOT NULL,
  stake numeric NOT NULL,
  odds_pct numeric NOT NULL,
  payout numeric NOT NULL,
  status text NOT NULL,
  settled_payout numeric,
  realized_pnl numeric,
  settled_at timestamptz,
  venue text NOT NULL,
  ticker text NOT NULL,
  placed_at timestamptz NOT NULL,
  payload jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (order_id)
);

-- Settlement history. The bet row still holds the current status, payout, and P&L.
-- external_id keeps a re-run from inserting the same settlement twice.
CREATE TABLE IF NOT EXISTS settlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bet_id text NOT NULL REFERENCES bets (id),
  status text NOT NULL,
  payout numeric,
  realized_pnl numeric,
  settled_at timestamptz NOT NULL,
  source text NOT NULL,
  external_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (external_id)
);

-- Deduped by id. lane is null on fight rows; kind is 'fight' for those.
CREATE TABLE IF NOT EXISTS calendar_entries (
  id text PRIMARY KEY,
  kind text,
  lane text,
  node text,
  start_at timestamptz NOT NULL,
  title text NOT NULL,
  status text NOT NULL,
  writer text NOT NULL,
  event_slug text,
  payload jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Room for PR #50. Empty until that branch records a final.
-- clock is the bout clock (the app field is `time`). The full row is payload.
CREATE TABLE IF NOT EXISTS fight_results (
  fight_slug text PRIMARY KEY,
  event text NOT NULL,
  winner text NOT NULL,
  method text NOT NULL,
  round integer NOT NULL,
  clock text NOT NULL,
  status text NOT NULL,
  opponent text,
  source text,
  payload jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Room for PR #50 versioned bet corrections. The applied version also lives
-- on the bet payload (correctionVersion) so a re-read does not apply twice.
CREATE TABLE IF NOT EXISTS bet_corrections (
  bet_id text NOT NULL REFERENCES bets (id),
  version integer NOT NULL,
  payload jsonb NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (bet_id, version)
);

-- Created only when missing. db:migrate skips this statement if the view exists.
CREATE VIEW operator_log AS
SELECT
  id,
  source,
  external_id,
  filled_at,
  symbol,
  side,
  quantity,
  price,
  venue,
  sleeve,
  result,
  log_only,
  note,
  payload,
  created_at
FROM fills;
