-- Fitness streams from Health Auto Export and the manual seed.
-- Idempotent: safe to re-run. Re-posting a day or workout upserts
-- on (source, external_id). See db/README.md.

CREATE TABLE IF NOT EXISTS fitness_metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  external_id text NOT NULL,
  metric text NOT NULL,
  day date NOT NULL,
  recorded_at timestamptz,
  qty numeric NOT NULL,
  units text NOT NULL,
  qty_min numeric,
  qty_max numeric,
  origin text NOT NULL,
  payload jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source, external_id)
);

CREATE INDEX IF NOT EXISTS fitness_metrics_day_idx ON fitness_metrics (day, metric);

CREATE TABLE IF NOT EXISTS fitness_workouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source text NOT NULL,
  external_id text NOT NULL,
  name text NOT NULL,
  started_at timestamptz NOT NULL,
  ended_at timestamptz,
  duration_sec numeric,
  distance_qty numeric,
  distance_units text,
  energy_kcal numeric,
  heart_rate_avg numeric,
  heart_rate_min numeric,
  heart_rate_max numeric,
  origin text NOT NULL,
  payload jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (source, external_id)
);

CREATE INDEX IF NOT EXISTS fitness_workouts_started_idx ON fitness_workouts (started_at);
