-- Login sessions, passkeys, and failed-attempt limits.
-- Idempotent. Number 005 leaves room for 004 (fight_breakdowns).
-- schema_migrations stores applied ids. A missing number does not block later files.
-- users is the hook for a second person. This deploy only signs in the owner
-- (username andres). That password and authenticator secret stay in env.
-- An operator is a later INSERT into users, not a change to this table:
--   INSERT INTO users (username, role, password_hash, totp_secret, created_at)
--   VALUES ('carla', 'operator', '<argon2id phc>', '<base32>', now());

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  role text NOT NULL CHECK (role IN ('owner', 'operator')),
  password_hash text,
  totp_secret text,
  created_at timestamptz NOT NULL,
  disabled_at timestamptz
);

CREATE TABLE IF NOT EXISTS auth_sessions (
  id_hash text PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id),
  created_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  renewed_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  user_agent text NOT NULL
);

CREATE INDEX IF NOT EXISTS auth_sessions_expires_idx ON auth_sessions (expires_at);

CREATE TABLE IF NOT EXISTS auth_passkeys (
  credential_id text PRIMARY KEY,
  public_key text NOT NULL,
  counter bigint NOT NULL,
  transports text,
  device_label text NOT NULL,
  created_at timestamptz NOT NULL,
  last_used_at timestamptz
);

CREATE TABLE IF NOT EXISTS auth_login_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash text NOT NULL,
  failed_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS auth_login_attempts_ip_idx ON auth_login_attempts (ip_hash, failed_at);

CREATE TABLE IF NOT EXISTS auth_global_lockout (
  id integer PRIMARY KEY,
  failures integer NOT NULL,
  locked_until timestamptz,
  backoff_sec integer NOT NULL,
  updated_at timestamptz NOT NULL
);
