-- Running and walking workouts posted by the Shortcuts ingest.
-- Number 010 leaves 006 and 007 for other in-flight branches.
-- The nightly shortcut re-sends the last 48 hours. UNIQUE (start_time, type)
-- makes that re-send an update. A richer row fills nulls and keeps the latest values.
-- Pace is derived on the server when distance is present.

CREATE TABLE IF NOT EXISTS fitness_shortcut_workouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time timestamptz NOT NULL,
  type text NOT NULL CHECK (type IN ('Running', 'Walking')),
  source_name text,
  duration_sec numeric NOT NULL,
  distance_m numeric,
  energy_kcal numeric,
  pace_sec_per_km numeric,
  pace_sec_per_mi numeric,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (start_time, type)
);

CREATE INDEX IF NOT EXISTS fitness_shortcut_workouts_start_idx
  ON fitness_shortcut_workouts (start_time);
