-- Build tracker items. Number 016 leaves 015 for the in-flight fills dedupe migration.
-- The migrator applies this id when 015 is absent.
-- steps is a JSON checklist. Percent is the share of steps marked done.
-- Live dates are noon America/Chicago. A second run inserts 0 rows.

CREATE TABLE IF NOT EXISTS build_items (
  id text PRIMARY KEY,
  title text NOT NULL,
  node text NOT NULL CHECK (node IN ('crypto', 'ai-stocks', 'fitness', 'finance', 'fight-desk', 'platform', 'youtube')),
  pr_number integer,
  status text NOT NULL CHECK (status IN ('live', 'in_progress', 'queued', 'blocked')),
  steps jsonb NOT NULL,
  next_step text,
  sort_order integer NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS build_items_node_sort_idx ON build_items (node, sort_order);

INSERT INTO build_items (id, title, node, pr_number, status, steps, next_step, sort_order, updated_at)
VALUES
  ('platform-login', 'Login: password + 6-digit code', 'platform', 60, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 10, '2026-10-08 12:00:00-05'),
  ('platform-build-budget', 'Build budget: one build per update', 'platform', 68, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 20, '2026-10-08 12:00:00-05'),
  ('platform-fitness-token', 'Fitness sync token on the Security page', 'platform', 67, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 30, '2026-10-08 12:00:00-05'),
  ('platform-fills-dedupe', 'Fills dedupe + lots totals across sleeves', 'platform', NULL, 'in_progress', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'merge, then verify on prod', 40, '2026-10-09 12:00:00-05'),
  ('platform-pwa', 'Installable iPhone app (PWA)', 'platform', 76, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'merge, then install on iPhone', 50, '2026-10-09 12:00:00-05'),
  ('platform-build-tracker', 'Build Tracker', 'platform', NULL, 'in_progress', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'merge, then verify on prod', 60, '2026-10-09 12:00:00-05'),
  ('platform-system-map', 'System Map: nodes, money flow, data sources, agents, governance lens', 'platform', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'Starts after Build Tracker merges', 70, '2026-10-09 12:00:00-05'),
  ('platform-public-mode', 'Public mode: a no-dollar screen-share toggle', 'platform', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'Starts after System Map', 75, '2026-10-09 12:00:00-05'),
  ('platform-carla-queue', 'Carla''s approval queue (pending and done)', 'platform', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, NULL, 80, '2026-10-09 12:00:00-05'),
  ('platform-control-room', 'Control Room', 'platform', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, NULL, 90, '2026-10-09 12:00:00-05'),
  ('crypto-day-bars', 'Home Crypto card: XRP and SUI day bars', 'crypto', 70, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 10, '2026-10-08 12:00:00-05'),
  ('crypto-mover-catalyst', 'Home Crypto card: top mover and catalyst lines', 'crypto', 71, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 20, '2026-10-08 12:00:00-05'),
  ('crypto-child-cards', 'Crypto child cards', 'crypto', 73, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 30, '2026-10-09 12:00:00-05'),
  ('crypto-lots-ledger', 'Lots ledger, position chart, HBAR removed', 'crypto', 74, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 40, '2026-10-09 12:00:00-05'),
  ('crypto-coinbase-parity', 'Coinbase parity: cb-agentic sleeve, SUI fill clean-up', 'crypto', 75, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 50, '2026-10-09 12:00:00-05'),
  ('crypto-xrp-trigger', 'XRP Trigger Watch', 'crypto', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, NULL, 100, '2026-10-09 12:00:00-05'),
  ('ai-core-eight', 'Core node at 8 names (PWR VRT GEV CEG NVDA TSM TSLA SPCX), ETN and HUBB retired', 'ai-stocks', 72, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 10, '2026-10-09 12:00:00-05'),
  ('ai-child-pages', 'AI stock child pages with role lines, plus the day % fix', 'ai-stocks', 73, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 20, '2026-10-09 12:00:00-05'),
  ('ai-catalyst-calendar', 'Catalyst Calendar', 'ai-stocks', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, NULL, 110, '2026-10-09 12:00:00-05'),
  ('fitness-health-sync', 'Apple Health step sync', 'fitness', 61, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 10, '2026-10-08 12:00:00-05'),
  ('fitness-runs', 'Runs tracking (Nike Run Club)', 'fitness', 69, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true},{"id":"founder-shortcut","label":"founder Shortcut set up","done":false}]'::jsonb, 'Andres builds the simple Steps Shortcut', 20, '2026-10-08 12:00:00-05'),
  ('finance-private-node', 'Private Finance node, five encrypted cards', 'finance', 64, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true},{"id":"first-snapshot","label":"first encrypted snapshot posted","done":false}]'::jsonb, 'Finance Desk posts the first snapshot', 10, '2026-10-08 12:00:00-05'),
  ('fight-bankroll', 'Bankroll', 'fight-desk', 57, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 10, '2026-10-08 12:00:00-05'),
  ('fight-breakdowns', 'Breakdowns', 'fight-desk', 59, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 20, '2026-10-08 12:00:00-05'),
  ('fight-bout-order', 'Bout order', 'fight-desk', 62, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 30, '2026-10-08 12:00:00-05'),
  ('youtube-gear', 'YouTube node with Gear child', 'youtube', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'Starts Mon Oct 12', 120, '2026-10-09 12:00:00-05')
ON CONFLICT (id) DO NOTHING;
