-- Owner PIN for the public/private switch, the lockout, and the mode log.
-- Number 017 leaves 015 for the in-flight fills dedupe migration.
-- The migrator applies this id when 015 is absent.
-- The PIN is stored only as an argon2id PHC string. A second run changes nothing.

CREATE TABLE IF NOT EXISTS owner_pin (
  id integer PRIMARY KEY CHECK (id = 1),
  pin_hash text NOT NULL CHECK (pin_hash LIKE '$argon2id$%'),
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS mode_switch_lockout (
  id integer PRIMARY KEY CHECK (id = 1),
  failures integer NOT NULL CHECK (failures >= 0),
  locked_until timestamptz,
  updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS mode_change_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  changed_at timestamptz NOT NULL,
  direction text NOT NULL CHECK (direction IN ('public', 'private')),
  outcome text NOT NULL CHECK (outcome IN ('success', 'failure')),
  user_agent text NOT NULL CHECK (user_agent IN ('iPhone', 'iPad', 'Android', 'Mobile', 'Mac', 'Windows', 'Linux', 'Other'))
);

CREATE INDEX IF NOT EXISTS mode_change_log_changed_idx ON mode_change_log (changed_at);
