/**
 * SQL shipped inside the server bundle.
 * db/migrations stays the reviewed source. A test checks these constants
 * match those files. Runtime migrate and the fitness page never read the folder.
 */

export const DOMAIN_SCHEMA_SQL = "-- Domain tables for Resonance stores.\n-- Idempotent: safe to re-run. New domains (money, fitness, fight results)\n-- land as later files in this folder. See db/README.md.\n\nCREATE TABLE IF NOT EXISTS schema_migrations (\n  id text PRIMARY KEY,\n  applied_at timestamptz NOT NULL DEFAULT now()\n);\n\nCREATE TABLE IF NOT EXISTS store_meta (\n  domain text PRIMARY KEY,\n  version integer NOT NULL,\n  updated_at timestamptz NOT NULL,\n  seeded_at timestamptz\n);\n\n-- Operator log rows. One row per fill. /log reads this table\n-- (and the operator_log view). Idempotent ingest key is (source, external_id).\nCREATE TABLE IF NOT EXISTS fills (\n  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  source text NOT NULL,\n  external_id text NOT NULL,\n  filled_at timestamptz NOT NULL,\n  symbol text NOT NULL,\n  side text,\n  quantity numeric,\n  price numeric,\n  venue text,\n  sleeve text,\n  result text NOT NULL,\n  log_only boolean NOT NULL DEFAULT false,\n  note text,\n  payload jsonb NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (source, external_id)\n);\n\nCREATE TABLE IF NOT EXISTS sleeve_prints (\n  ticker text NOT NULL,\n  sleeve_id text NOT NULL,\n  quantity text NOT NULL,\n  PRIMARY KEY (ticker, sleeve_id)\n);\n\n-- id stays the primary key. order_id is the idempotency key (falls back to id).\nCREATE TABLE IF NOT EXISTS bets (\n  id text PRIMARY KEY,\n  order_id text NOT NULL,\n  event text NOT NULL,\n  fight text NOT NULL,\n  fight_slug text NOT NULL,\n  pick text NOT NULL,\n  stake numeric NOT NULL,\n  odds_pct numeric NOT NULL,\n  payout numeric NOT NULL,\n  status text NOT NULL,\n  settled_payout numeric,\n  realized_pnl numeric,\n  settled_at timestamptz,\n  venue text NOT NULL,\n  ticker text NOT NULL,\n  placed_at timestamptz NOT NULL,\n  payload jsonb NOT NULL,\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (order_id)\n);\n\n-- Settlement history. The bet row still holds the current status, payout, and P&L.\n-- external_id keeps a re-run from inserting the same settlement twice.\nCREATE TABLE IF NOT EXISTS settlements (\n  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  bet_id text NOT NULL REFERENCES bets (id),\n  status text NOT NULL,\n  payout numeric,\n  realized_pnl numeric,\n  settled_at timestamptz NOT NULL,\n  source text NOT NULL,\n  external_id text NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (external_id)\n);\n\n-- Deduped by id. lane is null on fight rows; kind is 'fight' for those.\nCREATE TABLE IF NOT EXISTS calendar_entries (\n  id text PRIMARY KEY,\n  kind text,\n  lane text,\n  node text,\n  start_at timestamptz NOT NULL,\n  title text NOT NULL,\n  status text NOT NULL,\n  writer text NOT NULL,\n  event_slug text,\n  payload jsonb NOT NULL,\n  updated_at timestamptz NOT NULL DEFAULT now()\n);\n\n-- Room for PR #50. Empty until that branch records a final.\n-- clock is the bout clock (the app field is `time`). The full row is payload.\nCREATE TABLE IF NOT EXISTS fight_results (\n  fight_slug text PRIMARY KEY,\n  event text NOT NULL,\n  winner text NOT NULL,\n  method text NOT NULL,\n  round integer NOT NULL,\n  clock text NOT NULL,\n  status text NOT NULL,\n  opponent text,\n  source text,\n  payload jsonb NOT NULL,\n  updated_at timestamptz NOT NULL DEFAULT now()\n);\n\n-- Room for PR #50 versioned bet corrections. The applied version also lives\n-- on the bet payload (correctionVersion) so a re-read does not apply twice.\nCREATE TABLE IF NOT EXISTS bet_corrections (\n  bet_id text NOT NULL REFERENCES bets (id),\n  version integer NOT NULL,\n  payload jsonb NOT NULL,\n  applied_at timestamptz NOT NULL DEFAULT now(),\n  PRIMARY KEY (bet_id, version)\n);\n\n-- Created only when missing. db:migrate skips this statement if the view exists.\nCREATE VIEW operator_log AS\nSELECT\n  id,\n  source,\n  external_id,\n  filled_at,\n  symbol,\n  side,\n  quantity,\n  price,\n  venue,\n  sleeve,\n  result,\n  log_only,\n  note,\n  payload,\n  created_at\nFROM fills;\n";

export const FITNESS_SCHEMA_SQL = "-- Fitness streams from Health Auto Export and the manual seed.\n-- Idempotent: safe to re-run. Re-posting a day or workout upserts\n-- on (source, external_id). See db/README.md.\n\nCREATE TABLE IF NOT EXISTS fitness_metrics (\n  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  source text NOT NULL,\n  external_id text NOT NULL,\n  metric text NOT NULL,\n  day date NOT NULL,\n  recorded_at timestamptz,\n  qty numeric NOT NULL,\n  units text NOT NULL,\n  qty_min numeric,\n  qty_max numeric,\n  origin text NOT NULL,\n  payload jsonb NOT NULL,\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (source, external_id)\n);\n\nCREATE INDEX IF NOT EXISTS fitness_metrics_day_idx ON fitness_metrics (day, metric);\n\nCREATE TABLE IF NOT EXISTS fitness_workouts (\n  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  source text NOT NULL,\n  external_id text NOT NULL,\n  name text NOT NULL,\n  started_at timestamptz NOT NULL,\n  ended_at timestamptz,\n  duration_sec numeric,\n  distance_qty numeric,\n  distance_units text,\n  energy_kcal numeric,\n  heart_rate_avg numeric,\n  heart_rate_min numeric,\n  heart_rate_max numeric,\n  origin text NOT NULL,\n  payload jsonb NOT NULL,\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (source, external_id)\n);\n\nCREATE INDEX IF NOT EXISTS fitness_workouts_started_idx ON fitness_workouts (started_at);\n";

export const BET_TIER_SQL =
  "-- Optional conviction on a ticket. Nullable. Existing rows stay NULL.\n-- Values used by the desk are STRONG and LEAN. Apply by hand in Neon\n-- if this environment shares the production database and skips prebuild migrate.\n\nALTER TABLE bets ADD COLUMN IF NOT EXISTS tier text;\n";

export const FIGHT_BREAKDOWNS_SQL = "-- Per-fight breakdowns for any event slug. UFC 332 stays on its static files.\n-- Idempotent. Production prebuild applies this the same way as 003_bet_tier.sql.\n\nCREATE TABLE IF NOT EXISTS fight_breakdowns (\n  event_slug text NOT NULL,\n  fight_slug text NOT NULL,\n  fight_n integer,\n  card text,\n  slot text,\n  division text,\n  rounds integer,\n  a_name text,\n  b_name text,\n  lean text,\n  conf text,\n  tier text,\n  method text,\n  why text,\n  x_factor text,\n  edges jsonb,\n  odds jsonb,\n  stats jsonb,\n  links jsonb,\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  PRIMARY KEY (event_slug, fight_slug)\n);\n";

export const AUTH_SCHEMA_SQL = `-- Login sessions, passkeys, and failed-attempt limits.
-- Idempotent. Number 005 leaves room for 004 (fight_breakdowns).
-- schema_migrations stores applied ids. A missing number does not block later files.
-- users is the hook for a second person. This deploy only signs in the owner
-- (username andres). That password and authenticator secret stay in env.
-- An operator is a later INSERT into users, not a change to this table:
--   INSERT INTO users (username, role, password_hash, totp_secret, created_at)
--   VALUES ('carla', 'operator', '<argon2id phc>', '<base32>', now());

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  role text NOT NULL CHECK (role IN ('owner', 'operator')),
  password_hash text,
  totp_secret text,
  created_at timestamptz NOT NULL,
  disabled_at timestamptz
);

CREATE TABLE IF NOT EXISTS auth_sessions (
  id_hash text PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id),
  created_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  renewed_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  user_agent text NOT NULL
);

CREATE INDEX IF NOT EXISTS auth_sessions_expires_idx ON auth_sessions (expires_at);

CREATE TABLE IF NOT EXISTS auth_passkeys (
  credential_id text PRIMARY KEY,
  public_key text NOT NULL,
  counter bigint NOT NULL,
  transports text,
  device_label text NOT NULL,
  created_at timestamptz NOT NULL,
  last_used_at timestamptz
);

CREATE TABLE IF NOT EXISTS auth_login_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash text NOT NULL,
  failed_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS auth_login_attempts_ip_idx ON auth_login_attempts (ip_hash, failed_at);

CREATE TABLE IF NOT EXISTS auth_global_lockout (
  id integer PRIMARY KEY,
  failures integer NOT NULL,
  locked_until timestamptz,
  backoff_sec integer NOT NULL,
  updated_at timestamptz NOT NULL
);
`

export const FINANCE_SCHEMA_SQL = `-- Encrypted finance snapshots. Aggregates only.
-- Number 008 leaves 006 and 007 for other in-flight branches.
-- The migrator applies this id when those numbers are absent.
-- payload_enc, iv, and tag are AES-256-GCM (base64 text). Plaintext is not stored.

CREATE TABLE IF NOT EXISTS finance_snapshots (
  as_of date PRIMARY KEY,
  schema_version integer NOT NULL,
  sha256 text NOT NULL,
  payload_enc text NOT NULL,
  iv text NOT NULL,
  tag text NOT NULL,
  stored_at timestamptz NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS finance_snapshots_sha256_idx ON finance_snapshots (sha256);
`;

export const RESET_RH_AGENTIC_SLEEVES_SQL = `-- One-off data correction (2026-10-08): reset rh-agentic sleeve prints to
-- Robinhood actual holdings after the 24-fill historical backfill stacked
-- quantities onto sleeves that already matched. Fills are untouched.
-- flare-vault is never stored in sleeve_prints (seed-only), so it cannot move here.
INSERT INTO sleeve_prints (ticker, sleeve_id, quantity) VALUES
  ('XRP',  'rh-agentic', '492.828'),
  ('SUI',  'rh-agentic', '0'),
  ('PWR',  'rh-agentic', '0.027119'),
  ('ETN',  'rh-agentic', '0.043380'),
  ('VRT',  'rh-agentic', '0.075844'),
  ('GEV',  'rh-agentic', '0.018766'),
  ('CEG',  'rh-agentic', '0.065243'),
  ('HUBB', 'rh-agentic', '0.039688'),
  ('HBAR', 'rh-agentic', '0')
ON CONFLICT (ticker, sleeve_id) DO UPDATE SET quantity = EXCLUDED.quantity;
`;

export const FITNESS_WORKOUTS_SQL = `-- Running and walking workouts posted by the Shortcuts ingest.
-- Number 010 leaves 006 and 007 for other in-flight branches.
-- The nightly shortcut re-sends the last 48 hours. UNIQUE (start_time, type)
-- makes that re-send an update. A richer row fills nulls and keeps the latest values.
-- Pace is derived on the server when distance is present.

CREATE TABLE IF NOT EXISTS fitness_shortcut_workouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time timestamptz NOT NULL,
  type text NOT NULL CHECK (type IN ('Running', 'Walking')),
  source_name text,
  duration_sec numeric NOT NULL,
  distance_m numeric,
  energy_kcal numeric,
  pace_sec_per_km numeric,
  pace_sec_per_mi numeric,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (start_time, type)
);

CREATE INDEX IF NOT EXISTS fitness_shortcut_workouts_start_idx
  ON fitness_shortcut_workouts (start_time);
`;

export const EMBEDDED_MIGRATIONS: { id: string; sql: string }[] = [
  { id: "001_domain_tables", sql: DOMAIN_SCHEMA_SQL },
  { id: "002_fitness", sql: FITNESS_SCHEMA_SQL },
  { id: "003_bet_tier", sql: BET_TIER_SQL },
  { id: "004_fight_breakdowns", sql: FIGHT_BREAKDOWNS_SQL },
  { id: "005_auth", sql: AUTH_SCHEMA_SQL },
  { id: "008_finance", sql: FINANCE_SCHEMA_SQL },
  { id: "009_reset_rh_agentic_sleeves", sql: RESET_RH_AGENTIC_SLEEVES_SQL },
  { id: "010_fitness_workouts", sql: FITNESS_WORKOUTS_SQL },
];
