/**
 * SQL shipped inside the server bundle.
 * db/migrations stays the reviewed source. A test checks these constants
 * match those files. Runtime migrate and the fitness page never read the folder.
 */

export const DOMAIN_SCHEMA_SQL = "-- Domain tables for Resonance stores.\n-- Idempotent: safe to re-run. New domains (money, fitness, fight results)\n-- land as later files in this folder. See db/README.md.\n\nCREATE TABLE IF NOT EXISTS schema_migrations (\n  id text PRIMARY KEY,\n  applied_at timestamptz NOT NULL DEFAULT now()\n);\n\nCREATE TABLE IF NOT EXISTS store_meta (\n  domain text PRIMARY KEY,\n  version integer NOT NULL,\n  updated_at timestamptz NOT NULL,\n  seeded_at timestamptz\n);\n\n-- Operator log rows. One row per fill. /log reads this table\n-- (and the operator_log view). Idempotent ingest key is (source, external_id).\nCREATE TABLE IF NOT EXISTS fills (\n  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  source text NOT NULL,\n  external_id text NOT NULL,\n  filled_at timestamptz NOT NULL,\n  symbol text NOT NULL,\n  side text,\n  quantity numeric,\n  price numeric,\n  venue text,\n  sleeve text,\n  result text NOT NULL,\n  log_only boolean NOT NULL DEFAULT false,\n  note text,\n  payload jsonb NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (source, external_id)\n);\n\nCREATE TABLE IF NOT EXISTS sleeve_prints (\n  ticker text NOT NULL,\n  sleeve_id text NOT NULL,\n  quantity text NOT NULL,\n  PRIMARY KEY (ticker, sleeve_id)\n);\n\n-- id stays the primary key. order_id is the idempotency key (falls back to id).\nCREATE TABLE IF NOT EXISTS bets (\n  id text PRIMARY KEY,\n  order_id text NOT NULL,\n  event text NOT NULL,\n  fight text NOT NULL,\n  fight_slug text NOT NULL,\n  pick text NOT NULL,\n  stake numeric NOT NULL,\n  odds_pct numeric NOT NULL,\n  payout numeric NOT NULL,\n  status text NOT NULL,\n  settled_payout numeric,\n  realized_pnl numeric,\n  settled_at timestamptz,\n  venue text NOT NULL,\n  ticker text NOT NULL,\n  placed_at timestamptz NOT NULL,\n  payload jsonb NOT NULL,\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (order_id)\n);\n\n-- Settlement history. The bet row still holds the current status, payout, and P&L.\n-- external_id keeps a re-run from inserting the same settlement twice.\nCREATE TABLE IF NOT EXISTS settlements (\n  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  bet_id text NOT NULL REFERENCES bets (id),\n  status text NOT NULL,\n  payout numeric,\n  realized_pnl numeric,\n  settled_at timestamptz NOT NULL,\n  source text NOT NULL,\n  external_id text NOT NULL,\n  created_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (external_id)\n);\n\n-- Deduped by id. lane is null on fight rows; kind is 'fight' for those.\nCREATE TABLE IF NOT EXISTS calendar_entries (\n  id text PRIMARY KEY,\n  kind text,\n  lane text,\n  node text,\n  start_at timestamptz NOT NULL,\n  title text NOT NULL,\n  status text NOT NULL,\n  writer text NOT NULL,\n  event_slug text,\n  payload jsonb NOT NULL,\n  updated_at timestamptz NOT NULL DEFAULT now()\n);\n\n-- Room for PR #50. Empty until that branch records a final.\n-- clock is the bout clock (the app field is `time`). The full row is payload.\nCREATE TABLE IF NOT EXISTS fight_results (\n  fight_slug text PRIMARY KEY,\n  event text NOT NULL,\n  winner text NOT NULL,\n  method text NOT NULL,\n  round integer NOT NULL,\n  clock text NOT NULL,\n  status text NOT NULL,\n  opponent text,\n  source text,\n  payload jsonb NOT NULL,\n  updated_at timestamptz NOT NULL DEFAULT now()\n);\n\n-- Room for PR #50 versioned bet corrections. The applied version also lives\n-- on the bet payload (correctionVersion) so a re-read does not apply twice.\nCREATE TABLE IF NOT EXISTS bet_corrections (\n  bet_id text NOT NULL REFERENCES bets (id),\n  version integer NOT NULL,\n  payload jsonb NOT NULL,\n  applied_at timestamptz NOT NULL DEFAULT now(),\n  PRIMARY KEY (bet_id, version)\n);\n\n-- Created only when missing. db:migrate skips this statement if the view exists.\nCREATE VIEW operator_log AS\nSELECT\n  id,\n  source,\n  external_id,\n  filled_at,\n  symbol,\n  side,\n  quantity,\n  price,\n  venue,\n  sleeve,\n  result,\n  log_only,\n  note,\n  payload,\n  created_at\nFROM fills;\n";

export const FITNESS_SCHEMA_SQL = "-- Fitness streams from Health Auto Export and the manual seed.\n-- Idempotent: safe to re-run. Re-posting a day or workout upserts\n-- on (source, external_id). See db/README.md.\n\nCREATE TABLE IF NOT EXISTS fitness_metrics (\n  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  source text NOT NULL,\n  external_id text NOT NULL,\n  metric text NOT NULL,\n  day date NOT NULL,\n  recorded_at timestamptz,\n  qty numeric NOT NULL,\n  units text NOT NULL,\n  qty_min numeric,\n  qty_max numeric,\n  origin text NOT NULL,\n  payload jsonb NOT NULL,\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (source, external_id)\n);\n\nCREATE INDEX IF NOT EXISTS fitness_metrics_day_idx ON fitness_metrics (day, metric);\n\nCREATE TABLE IF NOT EXISTS fitness_workouts (\n  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n  source text NOT NULL,\n  external_id text NOT NULL,\n  name text NOT NULL,\n  started_at timestamptz NOT NULL,\n  ended_at timestamptz,\n  duration_sec numeric,\n  distance_qty numeric,\n  distance_units text,\n  energy_kcal numeric,\n  heart_rate_avg numeric,\n  heart_rate_min numeric,\n  heart_rate_max numeric,\n  origin text NOT NULL,\n  payload jsonb NOT NULL,\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  UNIQUE (source, external_id)\n);\n\nCREATE INDEX IF NOT EXISTS fitness_workouts_started_idx ON fitness_workouts (started_at);\n";

export const BET_TIER_SQL =
  "-- Optional conviction on a ticket. Nullable. Existing rows stay NULL.\n-- Values used by the desk are STRONG and LEAN. Apply by hand in Neon\n-- if this environment shares the production database and skips prebuild migrate.\n\nALTER TABLE bets ADD COLUMN IF NOT EXISTS tier text;\n";

export const FIGHT_BREAKDOWNS_SQL = "-- Per-fight breakdowns for any event slug. UFC 332 stays on its static files.\n-- Idempotent. Production prebuild applies this the same way as 003_bet_tier.sql.\n\nCREATE TABLE IF NOT EXISTS fight_breakdowns (\n  event_slug text NOT NULL,\n  fight_slug text NOT NULL,\n  fight_n integer,\n  card text,\n  slot text,\n  division text,\n  rounds integer,\n  a_name text,\n  b_name text,\n  lean text,\n  conf text,\n  tier text,\n  method text,\n  why text,\n  x_factor text,\n  edges jsonb,\n  odds jsonb,\n  stats jsonb,\n  links jsonb,\n  updated_at timestamptz NOT NULL DEFAULT now(),\n  PRIMARY KEY (event_slug, fight_slug)\n);\n";

export const AUTH_SCHEMA_SQL = `-- Login sessions, passkeys, and failed-attempt limits.
-- Idempotent. Number 005 leaves room for 004 (fight_breakdowns).
-- schema_migrations stores applied ids. A missing number does not block later files.
-- users is the hook for a second person. This deploy only signs in the owner
-- (username andres). That password and authenticator secret stay in env.
-- An operator is a later INSERT into users, not a change to this table:
--   INSERT INTO users (username, role, password_hash, totp_secret, created_at)
--   VALUES ('carla', 'operator', '<argon2id phc>', '<base32>', now());

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  role text NOT NULL CHECK (role IN ('owner', 'operator')),
  password_hash text,
  totp_secret text,
  created_at timestamptz NOT NULL,
  disabled_at timestamptz
);

CREATE TABLE IF NOT EXISTS auth_sessions (
  id_hash text PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users (id),
  created_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL,
  renewed_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  user_agent text NOT NULL
);

CREATE INDEX IF NOT EXISTS auth_sessions_expires_idx ON auth_sessions (expires_at);

CREATE TABLE IF NOT EXISTS auth_passkeys (
  credential_id text PRIMARY KEY,
  public_key text NOT NULL,
  counter bigint NOT NULL,
  transports text,
  device_label text NOT NULL,
  created_at timestamptz NOT NULL,
  last_used_at timestamptz
);

CREATE TABLE IF NOT EXISTS auth_login_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash text NOT NULL,
  failed_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS auth_login_attempts_ip_idx ON auth_login_attempts (ip_hash, failed_at);

CREATE TABLE IF NOT EXISTS auth_global_lockout (
  id integer PRIMARY KEY,
  failures integer NOT NULL,
  locked_until timestamptz,
  backoff_sec integer NOT NULL,
  updated_at timestamptz NOT NULL
);
`

export const FINANCE_SCHEMA_SQL = `-- Encrypted finance snapshots. Aggregates only.
-- Number 008 leaves 006 and 007 for other in-flight branches.
-- The migrator applies this id when those numbers are absent.
-- payload_enc, iv, and tag are AES-256-GCM (base64 text). Plaintext is not stored.

CREATE TABLE IF NOT EXISTS finance_snapshots (
  as_of date PRIMARY KEY,
  schema_version integer NOT NULL,
  sha256 text NOT NULL,
  payload_enc text NOT NULL,
  iv text NOT NULL,
  tag text NOT NULL,
  stored_at timestamptz NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS finance_snapshots_sha256_idx ON finance_snapshots (sha256);
`;

export const RESET_RH_AGENTIC_SLEEVES_SQL = `-- One-off data correction (2026-10-08): reset rh-agentic sleeve prints to
-- Robinhood actual holdings after the 24-fill historical backfill stacked
-- quantities onto sleeves that already matched. Fills are untouched.
-- flare-vault is never stored in sleeve_prints (seed-only), so it cannot move here.
INSERT INTO sleeve_prints (ticker, sleeve_id, quantity) VALUES
  ('XRP',  'rh-agentic', '492.828'),
  ('SUI',  'rh-agentic', '0'),
  ('PWR',  'rh-agentic', '0.027119'),
  ('ETN',  'rh-agentic', '0.043380'),
  ('VRT',  'rh-agentic', '0.075844'),
  ('GEV',  'rh-agentic', '0.018766'),
  ('CEG',  'rh-agentic', '0.065243'),
  ('HUBB', 'rh-agentic', '0.039688'),
  ('HBAR', 'rh-agentic', '0')
ON CONFLICT (ticker, sleeve_id) DO UPDATE SET quantity = EXCLUDED.quantity;
`;

export const FITNESS_WORKOUTS_SQL = `-- Running and walking workouts posted by the Shortcuts ingest.
-- Number 010 leaves 006 and 007 for other in-flight branches.
-- The nightly shortcut re-sends the last 48 hours. UNIQUE (start_time, type)
-- makes that re-send an update. A richer row fills nulls and keeps the latest values.
-- distance_source is 'workout' when the workout carried a distance, or 'derived'
-- when the server summed Walking + Running Distance samples inside the workout.
-- An explicit workout distance replaces a derived one. Pace is recomputed from the kept distance.

CREATE TABLE IF NOT EXISTS fitness_shortcut_workouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time timestamptz NOT NULL,
  type text NOT NULL CHECK (type IN ('Running', 'Walking')),
  source_name text,
  duration_sec numeric NOT NULL,
  distance_m numeric,
  distance_source text CHECK (distance_source IS NULL OR distance_source IN ('workout', 'derived')),
  energy_kcal numeric,
  pace_sec_per_km numeric,
  pace_sec_per_mi numeric,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (start_time, type)
);

CREATE INDEX IF NOT EXISTS fitness_shortcut_workouts_start_idx
  ON fitness_shortcut_workouts (start_time);
`;

export const XRP_AGENTIC_SLEEVE_SQL = `-- One-off data correction: the 2026-09-18 sell of 10 XRP
-- (order 6aad6b7a-415a-4895-b43c-72c0eca79a55) was stored with a null
-- sleeve and no venue, so per-sleeve sums skipped those 10 tokens.
-- Sets that one row to rh-agentic / robinhood. A second run updates 0 rows.
-- Does not write sleeve_prints and does not re-apply sleeve math.
-- The migrate step also writes sleeve and venue into this row's payload,
-- because the operator log reads the payload. Other null-sleeve rows stay null.

UPDATE fills
SET sleeve = 'rh-agentic',
    venue = 'robinhood'
WHERE symbol = 'XRP'
  AND sleeve IS NULL
  AND (
    external_id = '6aad6b7a-415a-4895-b43c-72c0eca79a55'
    OR external_id LIKE '%6aad6b7a-415a-4895-b43c-72c0eca79a55'
    OR payload->>'orderId' = '6aad6b7a-415a-4895-b43c-72c0eca79a55'
  )
RETURNING external_id;
`;

export const SUI_AGENTIC_SLEEVE_SQL = `-- One-off data correction: the 2026-09-18 buy of 16.931 SUI
-- (order 6aad6b8e-f2a6-4be3-a803-65940a748d8d, the SUI leg of the
-- XRP→SUI swap) was stored with a null sleeve and no venue.
-- Sets that one row to rh-agentic / robinhood. A second run updates 0 rows.
-- Does not write sleeve_prints and does not re-apply sleeve math.
-- The migrate step also writes sleeve and venue into this row's payload,
-- because the operator log reads the payload. Other null-sleeve rows stay null.

UPDATE fills
SET sleeve = 'rh-agentic',
    venue = 'robinhood'
WHERE symbol = 'SUI'
  AND sleeve IS NULL
  AND (
    external_id = '6aad6b8e-f2a6-4be3-a803-65940a748d8d'
    OR external_id LIKE '%6aad6b8e-f2a6-4be3-a803-65940a748d8d'
    OR payload->>'orderId' = '6aad6b8e-f2a6-4be3-a803-65940a748d8d'
  )
RETURNING external_id;
`;

export const SUI_COINBASE_BACKFILL_SQL = `-- Backfill the two Coinbase SUI buys that already sit in the coinbase
-- sleeve quantity (16.8 + 16.9 = 33.7). Inserts a fill only when that
-- order id is absent. backfill is true so a later replay does not move
-- the sleeve. Does not write sleeve_prints and does not re-apply sleeve math.
-- A second run inserts 0 rows.

INSERT INTO fills (
  source, external_id, filled_at, symbol, side, quantity, price, venue, sleeve, result, payload
)
SELECT
  'coinbase',
  'coinbase:6bab89a3-fdbb-4768-92f4-dbb5654bf1f3',
  '2026-09-18T12:49:23-05:00'::timestamptz,
  'SUI',
  'buy',
  '16.8'::numeric,
  '0.8020710385'::numeric,
  'coinbase',
  'coinbase',
  'filled',
  '{"time":"2026-09-18T12:49:23-05:00","symbol":"SUI","side":"buy","quantity":"16.8","price":"0.8020710385","orderId":"6bab89a3-fdbb-4768-92f4-dbb5654bf1f3","result":"filled","venue":"coinbase","sleeve":"coinbase","idempotencyKey":"coinbase:6bab89a3-fdbb-4768-92f4-dbb5654bf1f3","backfill":true}'::jsonb
WHERE NOT EXISTS (
  SELECT 1 FROM fills
  WHERE external_id = '6bab89a3-fdbb-4768-92f4-dbb5654bf1f3'
     OR external_id LIKE '%6bab89a3-fdbb-4768-92f4-dbb5654bf1f3'
     OR payload->>'orderId' = '6bab89a3-fdbb-4768-92f4-dbb5654bf1f3'
)
RETURNING external_id;

INSERT INTO fills (
  source, external_id, filled_at, symbol, side, quantity, price, venue, sleeve, result, payload
)
SELECT
  'coinbase',
  'coinbase:4ef87d64-62b4-42f1-ac48-7db6941d5ba8',
  '2026-09-18T12:51:58-05:00'::timestamptz,
  'SUI',
  'buy',
  '16.9'::numeric,
  '0.8019'::numeric,
  'coinbase',
  'coinbase',
  'filled',
  '{"time":"2026-09-18T12:51:58-05:00","symbol":"SUI","side":"buy","quantity":"16.9","price":"0.8019","orderId":"4ef87d64-62b4-42f1-ac48-7db6941d5ba8","result":"filled","venue":"coinbase","sleeve":"coinbase","idempotencyKey":"coinbase:4ef87d64-62b4-42f1-ac48-7db6941d5ba8","backfill":true}'::jsonb
WHERE NOT EXISTS (
  SELECT 1 FROM fills
  WHERE external_id = '4ef87d64-62b4-42f1-ac48-7db6941d5ba8'
     OR external_id LIKE '%4ef87d64-62b4-42f1-ac48-7db6941d5ba8'
     OR payload->>'orderId' = '4ef87d64-62b4-42f1-ac48-7db6941d5ba8'
)
RETURNING external_id;
`;

export const CB_AGENTIC_XRP_SQL = `-- Seed the Coinbase Agentic XRP sleeve (portfolio transfer, no trades).
-- Inserts XRP / cb-agentic / 10 only when that print is absent.
-- Does not update an existing quantity and does not write any other sleeve.

INSERT INTO sleeve_prints (ticker, sleeve_id, quantity)
SELECT 'XRP', 'cb-agentic', '10'
WHERE NOT EXISTS (
  SELECT 1 FROM sleeve_prints
  WHERE ticker = 'XRP' AND sleeve_id = 'cb-agentic'
)
RETURNING sleeve_id;
`;

export const DEDUPE_RETAGGED_FILLS_SQL = "-- 011 and 012 set sleeve rh-agentic and venue robinhood on two legacy\n-- fills but left source as 'seed'. The next full envelope save keyed\n-- source off venue, missed those rows, and inserted robinhood copies\n-- with the same external_id. Sleeve prints were not doubled.\n--\n-- For exactly these external_ids (the bare order id, or the seed: form\n-- fillRowKey stored):\n--   seed and robinhood both present: delete only the seed row\n--   only seed present: set source to robinhood\n--   robinhood row missing sleeve or venue: set rh-agentic / robinhood\n-- The migrate step also fills a robinhood payload that lacks those fields\n-- and logs how many other external_ids still sit under more than one source.\n-- It does not delete those others, and it does not change sleeve quantities.\n-- A second run changes 0 rows.\n\nDELETE FROM fills\nWHERE source = 'seed'\n  AND external_id IN (\n    '6aad6b7a-415a-4895-b43c-72c0eca79a55',\n    'seed:6aad6b7a-415a-4895-b43c-72c0eca79a55',\n    '6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n    'seed:6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n  )\n  AND external_id IN (\n    SELECT robinhood.external_id\n    FROM fills AS robinhood\n    WHERE robinhood.source = 'robinhood'\n  )\nRETURNING external_id;\n\nUPDATE fills\nSET source = 'robinhood',\n    sleeve = CASE WHEN sleeve IS NULL OR sleeve = '' THEN 'rh-agentic' ELSE sleeve END,\n    venue = CASE WHEN venue IS NULL OR venue = '' THEN 'robinhood' ELSE venue END\nWHERE source = 'seed'\n  AND external_id IN (\n    '6aad6b7a-415a-4895-b43c-72c0eca79a55',\n    'seed:6aad6b7a-415a-4895-b43c-72c0eca79a55',\n    '6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n    'seed:6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n  )\nRETURNING external_id;\n\nUPDATE fills\nSET sleeve = 'rh-agentic',\n    venue = 'robinhood'\nWHERE source = 'robinhood'\n  AND external_id IN (\n    '6aad6b7a-415a-4895-b43c-72c0eca79a55',\n    'seed:6aad6b7a-415a-4895-b43c-72c0eca79a55',\n    '6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n    'seed:6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n  )\n  AND (\n    sleeve IS NULL\n    OR sleeve = ''\n    OR sleeve <> 'rh-agentic'\n    OR venue IS NULL\n    OR venue = ''\n    OR venue <> 'robinhood'\n  )\nRETURNING external_id;\n\nSELECT count(*)::int AS multi_source_external_ids\nFROM (\n  SELECT DISTINCT older.external_id\n  FROM fills AS older\n  INNER JOIN fills AS newer\n    ON older.external_id = newer.external_id\n   AND older.source <> newer.source\n) AS multi_source;\n";

export const BUILD_ITEMS_SQL = `-- Build tracker items. Number 016 leaves 015 for the in-flight fills dedupe migration.
-- The migrator applies this id when 015 is absent.
-- steps is a JSON checklist. Percent is the share of steps marked done.
-- Live dates are noon America/Chicago. A second run inserts 0 rows.

CREATE TABLE IF NOT EXISTS build_items (
  id text PRIMARY KEY,
  title text NOT NULL,
  node text NOT NULL CHECK (node IN ('crypto', 'ai-stocks', 'fitness', 'finance', 'fight-desk', 'platform', 'youtube')),
  pr_number integer,
  status text NOT NULL CHECK (status IN ('live', 'in_progress', 'queued', 'blocked')),
  steps jsonb NOT NULL,
  next_step text,
  sort_order integer NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS build_items_node_sort_idx ON build_items (node, sort_order);

INSERT INTO build_items (id, title, node, pr_number, status, steps, next_step, sort_order, updated_at)
VALUES
  ('platform-login', 'Login: password + 6-digit code', 'platform', 60, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 10, '2026-10-08 12:00:00-05'),
  ('platform-build-budget', 'Build budget: one build per update', 'platform', 68, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 20, '2026-10-08 12:00:00-05'),
  ('platform-fitness-token', 'Fitness sync token on the Security page', 'platform', 67, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 30, '2026-10-08 12:00:00-05'),
  ('platform-fills-dedupe', 'Fills dedupe + lots totals across sleeves', 'platform', NULL, 'in_progress', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'merge, then verify on prod', 40, '2026-10-09 12:00:00-05'),
  ('platform-pwa', 'Installable iPhone app (PWA)', 'platform', 76, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'merge, then install on iPhone', 50, '2026-10-09 12:00:00-05'),
  ('platform-build-tracker', 'Build Tracker', 'platform', NULL, 'in_progress', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'merge, then verify on prod', 60, '2026-10-09 12:00:00-05'),
  ('platform-system-map', 'System Map: nodes, money flow, data sources, agents, governance lens', 'platform', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'Starts after Build Tracker merges', 70, '2026-10-09 12:00:00-05'),
  ('platform-public-mode', 'Public mode: a no-dollar screen-share toggle', 'platform', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'Starts after System Map', 75, '2026-10-09 12:00:00-05'),
  ('platform-carla-queue', 'Carla''s approval queue (pending and done)', 'platform', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, NULL, 80, '2026-10-09 12:00:00-05'),
  ('platform-control-room', 'Control Room', 'platform', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, NULL, 90, '2026-10-09 12:00:00-05'),
  ('crypto-day-bars', 'Home Crypto card: XRP and SUI day bars', 'crypto', 70, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 10, '2026-10-08 12:00:00-05'),
  ('crypto-mover-catalyst', 'Home Crypto card: top mover and catalyst lines', 'crypto', 71, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 20, '2026-10-08 12:00:00-05'),
  ('crypto-child-cards', 'Crypto child cards', 'crypto', 73, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 30, '2026-10-09 12:00:00-05'),
  ('crypto-lots-ledger', 'Lots ledger, position chart, HBAR removed', 'crypto', 74, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 40, '2026-10-09 12:00:00-05'),
  ('crypto-coinbase-parity', 'Coinbase parity: cb-agentic sleeve, SUI fill clean-up', 'crypto', 75, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 50, '2026-10-09 12:00:00-05'),
  ('crypto-xrp-trigger', 'XRP Trigger Watch', 'crypto', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, NULL, 100, '2026-10-09 12:00:00-05'),
  ('ai-core-eight', 'Core node at 8 names (PWR VRT GEV CEG NVDA TSM TSLA SPCX), ETN and HUBB retired', 'ai-stocks', 72, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 10, '2026-10-09 12:00:00-05'),
  ('ai-child-pages', 'AI stock child pages with role lines, plus the day % fix', 'ai-stocks', 73, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 20, '2026-10-09 12:00:00-05'),
  ('ai-catalyst-calendar', 'Catalyst Calendar', 'ai-stocks', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, NULL, 110, '2026-10-09 12:00:00-05'),
  ('fitness-health-sync', 'Apple Health step sync', 'fitness', 61, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 10, '2026-10-08 12:00:00-05'),
  ('fitness-runs', 'Runs tracking (Nike Run Club)', 'fitness', 69, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true},{"id":"founder-shortcut","label":"founder Shortcut set up","done":false}]'::jsonb, 'Andres builds the simple Steps Shortcut', 20, '2026-10-08 12:00:00-05'),
  ('finance-private-node', 'Private Finance node, five encrypted cards', 'finance', 64, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true},{"id":"first-snapshot","label":"first encrypted snapshot posted","done":false}]'::jsonb, 'Finance Desk posts the first snapshot', 10, '2026-10-08 12:00:00-05'),
  ('fight-bankroll', 'Bankroll', 'fight-desk', 57, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 10, '2026-10-08 12:00:00-05'),
  ('fight-breakdowns', 'Breakdowns', 'fight-desk', 59, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 20, '2026-10-08 12:00:00-05'),
  ('fight-bout-order', 'Bout order', 'fight-desk', 62, 'live', '[{"id":"spec","label":"spec written","done":true},{"id":"pr-open","label":"PR open","done":true},{"id":"tests-build","label":"local tests and build pass","done":true},{"id":"merged","label":"merged","done":true},{"id":"verified-prod","label":"verified on prod","done":true}]'::jsonb, NULL, 30, '2026-10-08 12:00:00-05'),
  ('youtube-gear', 'YouTube node with Gear child', 'youtube', NULL, 'queued', '[{"id":"spec","label":"spec written","done":false},{"id":"pr-open","label":"PR open","done":false},{"id":"tests-build","label":"local tests and build pass","done":false},{"id":"merged","label":"merged","done":false},{"id":"verified-prod","label":"verified on prod","done":false}]'::jsonb, 'Starts Mon Oct 12', 120, '2026-10-09 12:00:00-05')
ON CONFLICT (id) DO NOTHING;
`;

export const DEDUPE_FILL_KEYS_SQL = "-- 015 matched only the bare order id and the seed: key. The old save\n-- wrote the duplicate under fillRowKey. With no idempotencyKey that key\n-- is robinhood:<orderId>, and source comes from the venue. 015 deleted\n-- nothing, then set the seed row's source to robinhood. Both copies remain.\n-- 017 and 018 are reserved. This id is 019.\n--\n-- For exactly these two order ids, when the group has exactly 2 rows:\n-- copy the loser into fills_dedupe_backup, then delete that id.\n-- The migrator runs these statements in one transaction.\n-- Keep the robinhood:<orderId> row when its source is robinhood and its\n-- sleeve is rh-agentic; otherwise keep the earliest row.\n-- One row: do nothing. Three or more: do nothing, and the review select\n-- names the order id. A second run changes 0 rows and does not copy again.\n-- Sleeve quantities are not written.\n\nCREATE TABLE IF NOT EXISTS fills_dedupe_backup (\n  migration_id text NOT NULL,\n  backed_up_at timestamptz NOT NULL DEFAULT now(),\n  id bigint NOT NULL,\n  source text NOT NULL,\n  external_id text NOT NULL,\n  filled_at timestamptz NOT NULL,\n  symbol text NOT NULL,\n  side text,\n  quantity numeric,\n  price numeric,\n  venue text,\n  sleeve text,\n  result text NOT NULL,\n  log_only boolean NOT NULL,\n  note text,\n  payload jsonb NOT NULL,\n  created_at timestamptz NOT NULL,\n  PRIMARY KEY (migration_id, id)\n);\n\nWITH members AS (\n  SELECT\n    id, source, external_id, filled_at, symbol, side, quantity, price,\n    venue, sleeve, result, log_only, note, payload, created_at\n  FROM fills\n  WHERE external_id IN (\n      '6aad6b7a-415a-4895-b43c-72c0eca79a55',\n      'seed:6aad6b7a-415a-4895-b43c-72c0eca79a55',\n      'robinhood:6aad6b7a-415a-4895-b43c-72c0eca79a55'\n    )\n    OR payload->>'orderId' = '6aad6b7a-415a-4895-b43c-72c0eca79a55'\n),\nsized AS (\n  SELECT count(*) AS n FROM members\n),\nkeeper AS (\n  SELECT id\n  FROM members\n  ORDER BY\n    CASE\n      WHEN external_id = 'robinhood:6aad6b7a-415a-4895-b43c-72c0eca79a55'\n       AND source = 'robinhood'\n       AND sleeve = 'rh-agentic' THEN 0\n      WHEN source = 'robinhood' AND sleeve = 'rh-agentic' THEN 1\n      ELSE 2\n    END,\n    created_at ASC,\n    id ASC\n  LIMIT 1\n),\ncopied AS (\n  INSERT INTO fills_dedupe_backup (\n    migration_id, backed_up_at,\n    id, source, external_id, filled_at, symbol, side, quantity, price,\n    venue, sleeve, result, log_only, note, payload, created_at\n  )\n  SELECT\n    '019_dedupe_fill_keys', now(),\n    m.id, m.source, m.external_id, m.filled_at, m.symbol,\n    m.side, m.quantity, m.price, m.venue, m.sleeve,\n    m.result, m.log_only, m.note, m.payload, m.created_at\n  FROM members AS m\n  JOIN sized ON sized.n = 2\n  JOIN keeper ON m.id <> keeper.id\n  ON CONFLICT (migration_id, id) DO NOTHING\n  RETURNING id, source, external_id\n)\nSELECT id, source, external_id FROM copied;\n\nDELETE FROM fills\nWHERE id = (\n  SELECT backup.id\n  FROM fills_dedupe_backup AS backup\n  JOIN (\n    SELECT count(*) AS n\n    FROM fills\n    WHERE external_id IN (\n        '6aad6b7a-415a-4895-b43c-72c0eca79a55',\n        'seed:6aad6b7a-415a-4895-b43c-72c0eca79a55',\n        'robinhood:6aad6b7a-415a-4895-b43c-72c0eca79a55'\n      )\n      OR payload->>'orderId' = '6aad6b7a-415a-4895-b43c-72c0eca79a55'\n  ) AS sized ON sized.n = 2\n  WHERE backup.migration_id = '019_dedupe_fill_keys'\n    AND (\n      backup.external_id IN (\n        '6aad6b7a-415a-4895-b43c-72c0eca79a55',\n        'seed:6aad6b7a-415a-4895-b43c-72c0eca79a55',\n        'robinhood:6aad6b7a-415a-4895-b43c-72c0eca79a55'\n      )\n      OR backup.payload->>'orderId' = '6aad6b7a-415a-4895-b43c-72c0eca79a55'\n    )\n  ORDER BY backup.id\n  LIMIT 1\n)\nRETURNING id, source, external_id;\n\nWITH members AS (\n  SELECT\n    id, source, external_id, filled_at, symbol, side, quantity, price,\n    venue, sleeve, result, log_only, note, payload, created_at\n  FROM fills\n  WHERE external_id IN (\n      '6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n      'seed:6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n      'robinhood:6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n    )\n    OR payload->>'orderId' = '6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n),\nsized AS (\n  SELECT count(*) AS n FROM members\n),\nkeeper AS (\n  SELECT id\n  FROM members\n  ORDER BY\n    CASE\n      WHEN external_id = 'robinhood:6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n       AND source = 'robinhood'\n       AND sleeve = 'rh-agentic' THEN 0\n      WHEN source = 'robinhood' AND sleeve = 'rh-agentic' THEN 1\n      ELSE 2\n    END,\n    created_at ASC,\n    id ASC\n  LIMIT 1\n),\ncopied AS (\n  INSERT INTO fills_dedupe_backup (\n    migration_id, backed_up_at,\n    id, source, external_id, filled_at, symbol, side, quantity, price,\n    venue, sleeve, result, log_only, note, payload, created_at\n  )\n  SELECT\n    '019_dedupe_fill_keys', now(),\n    m.id, m.source, m.external_id, m.filled_at, m.symbol,\n    m.side, m.quantity, m.price, m.venue, m.sleeve,\n    m.result, m.log_only, m.note, m.payload, m.created_at\n  FROM members AS m\n  JOIN sized ON sized.n = 2\n  JOIN keeper ON m.id <> keeper.id\n  ON CONFLICT (migration_id, id) DO NOTHING\n  RETURNING id, source, external_id\n)\nSELECT id, source, external_id FROM copied;\n\nDELETE FROM fills\nWHERE id = (\n  SELECT backup.id\n  FROM fills_dedupe_backup AS backup\n  JOIN (\n    SELECT count(*) AS n\n    FROM fills\n    WHERE external_id IN (\n        '6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n        'seed:6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n        'robinhood:6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n      )\n      OR payload->>'orderId' = '6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n  ) AS sized ON sized.n = 2\n  WHERE backup.migration_id = '019_dedupe_fill_keys'\n    AND (\n      backup.external_id IN (\n        '6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n        'seed:6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n        'robinhood:6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n      )\n      OR backup.payload->>'orderId' = '6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n    )\n  ORDER BY backup.id\n  LIMIT 1\n)\nRETURNING id, source, external_id;\n\nSELECT order_id AS manual_review_order_id, row_count\nFROM (\n  SELECT '6aad6b7a-415a-4895-b43c-72c0eca79a55' AS order_id, count(*)::int AS row_count\n  FROM fills\n  WHERE external_id IN (\n      '6aad6b7a-415a-4895-b43c-72c0eca79a55',\n      'seed:6aad6b7a-415a-4895-b43c-72c0eca79a55',\n      'robinhood:6aad6b7a-415a-4895-b43c-72c0eca79a55'\n    )\n    OR payload->>'orderId' = '6aad6b7a-415a-4895-b43c-72c0eca79a55'\n) AS grouped\nWHERE row_count >= 3\nUNION ALL\nSELECT order_id, row_count\nFROM (\n  SELECT '6aad6b8e-f2a6-4be3-a803-65940a748d8d' AS order_id, count(*)::int AS row_count\n  FROM fills\n  WHERE external_id IN (\n      '6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n      'seed:6aad6b8e-f2a6-4be3-a803-65940a748d8d',\n      'robinhood:6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n    )\n    OR payload->>'orderId' = '6aad6b8e-f2a6-4be3-a803-65940a748d8d'\n) AS grouped\nWHERE row_count >= 3;\n";

export const EMBEDDED_MIGRATIONS: { id: string; sql: string }[] = [
  { id: "001_domain_tables", sql: DOMAIN_SCHEMA_SQL },
  { id: "002_fitness", sql: FITNESS_SCHEMA_SQL },
  { id: "003_bet_tier", sql: BET_TIER_SQL },
  { id: "004_fight_breakdowns", sql: FIGHT_BREAKDOWNS_SQL },
  { id: "005_auth", sql: AUTH_SCHEMA_SQL },
  { id: "008_finance", sql: FINANCE_SCHEMA_SQL },
  { id: "009_reset_rh_agentic_sleeves", sql: RESET_RH_AGENTIC_SLEEVES_SQL },
  { id: "010_fitness_workouts", sql: FITNESS_WORKOUTS_SQL },
  { id: "011_xrp_agentic_sleeve", sql: XRP_AGENTIC_SLEEVE_SQL },
  { id: "012_sui_agentic_sleeve", sql: SUI_AGENTIC_SLEEVE_SQL },
  { id: "013_sui_coinbase_backfill", sql: SUI_COINBASE_BACKFILL_SQL },
  { id: "014_cb_agentic_xrp", sql: CB_AGENTIC_XRP_SQL },
  { id: "015_dedupe_retagged_fills", sql: DEDUPE_RETAGGED_FILLS_SQL },
  { id: "016_build_items", sql: BUILD_ITEMS_SQL },
  { id: "019_dedupe_fill_keys", sql: DEDUPE_FILL_KEYS_SQL },
];
